name: API Service

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/*
      - Dockerfile

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: ["english", "chinese", "arabic", "spanish", "french", "german"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_SECRET }}
      - name: Build & push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          build-args: LANGUAGE=${{ matrix.lang }}
          push: true
          context: .
          tags: ghcr.io/linguistic/corenlp-${{ matrix.lang }}:latest
